# Generated by Django 3.0.7 on 2020-07-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_handmadecomponents'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastillaComponents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
